[project]
name = "song-classifier"
version = "0.1.0"
description = "A cli tool to tag music sets with metadata"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mutagen>=1.47.0",
    "openai>=1.40.0",
    "textual>=0.79.1",
    "webdavclient3==3.14.6",
]
